config/routes.rb
SampleApp::Application.routes.draw do
  

  get "password_resets/new"
  resources :users do
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  root 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/thankyou.rb
class Thankyou < ActiveRecord::Base


  belongs_to :sender, class_name: "User" # note, implied FK "sender_id"
  belongs_to :recipient, class_name: "User"

  validates :message,  presence: true
  validates :recipient_id,  presence: true
  validates :sender_id,  presence: true

end

app/models/user.rb
class User < ActiveRecord::Base


  
	before_save { self.email = email.downcase }

  before_create :create_remember_token

  has_many :thankyous_sent, foreign_key: "sender_id" , class_name: "Thankyou"
  has_many :thankyous_received, foreign_key: "recipient_id" , class_name: "Thankyou"

  has_many :sent_to_users, through: :thankyous_sent, source: :recipient
  has_many :received_from_users, through: :thankyous_received, source: :sender



	validates(:name, presence: true, length: {maximum: 50})
#	validates :name,  presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX =	/\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates(:email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false })
	 
	has_secure_password
	validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def send_password_reset
    generate_password_reset_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    self.save!(validate: false)
    UserMailer.password_reset(self).deliver
  end

  # Thankyou feed

  def thankyou_feed

    Thankyou.where(recipient:self)

  end

  # Thankyou create/ delete methods- not sure these are actually necessary just do them in the controller

  def create_message(r, m)

    # self.thankyous_sent.create(message: "test message", sender_id: self.id, recipient_id: r.id)
    self.thankyous_sent.create(message: m, sender: self, recipient: r)

  end

  # delete_message???


  private

    def generate_password_reset_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end


    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
	  user = User.find_by_email(params[:email])

	  if user
		  user.send_password_reset 
		  redirect_to root_url, :notice => "Email sent with password reset instructions."
		else
			redirect_to root_url, :notice => "Password reset failed."
		end
	end

	def edit
	  @user = User.find_by_password_reset_token!(params[:id])
	end

	def update
	  @user = User.find_by_password_reset_token!(params[:id])
	  
	  if @user.password_reset_sent_at < 2.hours.ago
	    redirect_to new_password_reset_path, :alert => "Password &crarr; 
	      reset has expired."

		elsif @user.update_attributes(user_params)

			logger.debug "@userhash: #{@user.attributes.inspect}"

	    redirect_to root_url, :notice => "Password has been reset."
	  
	  else
	    render :edit
	  end
	end
  
  private  

    def user_params
      params.require(:user).permit(:password, :password_confirmation )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	
  	user = User.find_by(email: params[:session][:email].downcase)

  	if user && user.authenticate(params[:session][:password])
  		sign_in user
      redirect_back_or user

  	else
  		# falsh now is for flasing on render rather than requests
  		flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
  	end

  end

  def destroy
    sign_out
    redirect_to root_url

  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home

  end

  def help
    @test1 = "about"
  end

	def about

    @test2 = "about"

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :signed_in_redirect, only: [:new, :create] 

  def new
  	
    @user = User.new 
   
  end

	def show
    @user = User.find(params[:id])
   
  end

  def index
    
    @users = User.paginate(page: params[:page])
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      # Handle a successful save.
			flash[:success] = "Welcome to the Sample App!"
    	redirect_to @user

    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end


  private  

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation )
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def signed_in_redirect
      if signed_in?
        redirect_to(root_url) 
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#returns the ful title on a per-page basis.

	def full_title(page_title)
		base_title = "Ruby on Rails Template"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper




end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    store_location
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  
   # short for:
   #  unless signed_in?
   #    flash[:notice] = "Please sign in."
   #    redirect_to signin_url
   #  end
  end

   def current_user=(user)
    @current_user = user
  end

	def current_user
    remember_token = User.digest(cookies[:remember_token])
    
		# ||= "or equals" only assigns if @current_user is nil, otherwise returns current user
    @current_user ||= User.find_by(remember_token: remember_token)
  
  end

  def current_user?(user)
    user == current_user
  end

	def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Rails Template", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
       

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<% provide(:title, 'Password Reset') %>

<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/relationships/create.js.erb
// $("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
// $("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
// $("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
// $("#followers").html('<%= @user.followers.count %>')

app/views/shared/_delete.html.erb
<% if current_user?(object_to_delete.user) %>
    <%= link_to "delete", object_to_delete, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: object_to_delete.content %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_home_not_signed_in.html.erb
<div class="center hero-unit">
  <h1>Matt's Rails template</h1>

  <h2>
    This is the home page for 
    <a href='#'>Matt's blank Rails template.</a>
    
  </h2>

  <%= link_to "Sign up now!", signup_path,
                              class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_home_signed_in.html.erb
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    



    </aside>
   

    <div class="span8">
      <h3>Micropost Feed</h3>
      
    </div>
  


  </div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

  <%= render 'shared/home_signed_in' %>

<% else %>

  <%= render 'shared/home_not_signed_in' %>

<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    
<!-- Here Rails infers that @users is a list of User objects; moreover, when called with a collection of users, Rails automatically iterates through them and renders each one with the _user.html.erb partial.
 -->
    <%= render @users %>

</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for( @user, size:100) %>
        <%= @user.name %>
      </h1>
    </section>
 


  </aside>
  <div class="span8">


  </div>

</div>